# Generated by Django 4.0.5 on 2022-06-03 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account_no', models.IntegerField()),
                ('bsb', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AllocationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Capex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('merchant', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Credit'), (2, 'Debit'), (3, 'Transfer')])),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='finance.allocation')),
                ('paid_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transaction_to', to='finance.account')),
                ('paid_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transaction_from', to='finance.account')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCapex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='finance.capex')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.transaction', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.allocation')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='CapexItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qty', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comment', models.CharField(max_length=1000)),
                ('capex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.capex')),
            ],
        ),
        migrations.CreateModel(
            name='CapexApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField()),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='capex_approver', to=settings.AUTH_USER_MODEL)),
                ('capex', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.capex')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='capex_requester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.PositiveSmallIntegerField(choices=[(1, 'Weekly'), (2, 'Fortnightly'), (3, 'Monthly'), (4, 'Quarterly'), (5, 'Annually')])),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rollover', models.BooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.account')),
                ('allocation', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='budget', to='finance.allocation')),
                ('excess_to_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='excess', to='finance.allocation')),
            ],
        ),
        migrations.CreateModel(
            name='AllocationTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Credit'), (2, 'Debit')])),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.allocation')),
            ],
        ),
        migrations.AddField(
            model_name='allocation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.allocationcategory'),
        ),
        migrations.CreateModel(
            name='AccountAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.bank'),
        ),
    ]
