# Generated by Django 4.0.5 on 2022-06-04 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_transaction_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationtransfer',
            name='transaction',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance.transaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactioncapex',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.transaction'),
        ),
        migrations.DeleteModel(
            name='TransactionAllocation',
        ),
    ]
