# Generated by Django 4.0.5 on 2022-06-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_allocationtransfer_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capexapproval',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Requested'), (2, 'Approved'), (3, 'Closed')], default=1),
            preserve_default=False,
        ),
    ]
