# Generated by Django 4.0.5 on 2022-06-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_capexapproval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capexitems',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
