# Generated by Django 4.0.5 on 2022-06-05 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_capexitems_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='capexitems',
            name='paid_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='finance.allocation'),
            preserve_default=False,
        ),
    ]
