# Generated by Django 4.0.5 on 2022-06-05 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_capexitems_paid_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capexitems',
            name='paid_from',
        ),
        migrations.AddField(
            model_name='capex',
            name='paid_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='finance.allocation'),
            preserve_default=False,
        ),
    ]
