# Generated by Django 4.0.5 on 2022-06-05 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_remove_capexitems_paid_from_capex_paid_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capexapproval',
            name='capex',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='finance.capex'),
        ),
    ]
