# Generated by Django 4.0.5 on 2022-06-05 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_capexapproval_capex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capexapproval',
            name='capex',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='status', to='finance.capex'),
        ),
    ]
