# Generated by Django 4.0.5 on 2022-06-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_transaction_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Credit'), (2, 'Debit'), (3, 'Transfer'), (3, 'Transfer Duplicate')]),
        ),
    ]
