# Generated by Django 4.0.5 on 2022-06-12 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_alter_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('basis', models.PositiveSmallIntegerField(choices=[(1, 'Weekly'), (2, 'Fortnightly'), (3, 'Monthly'), (4, 'Quarterly'), (5, 'Annually')])),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rollover', models.BooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.account')),
                ('allocation', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='budget_lock', to='finance.allocation')),
                ('excess_to_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='excess_lock', to='finance.allocation')),
            ],
        ),
    ]
