# Generated by Django 4.0.5 on 2022-06-16 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_alter_allocation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetlock',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='budget_lock', to='finance.allocation'),
        ),
    ]
