# Generated by Django 4.0.5 on 2022-06-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_alter_budgetlock_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capexapproval',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Requested'), (2, 'Approved'), (3, 'Closed')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Credit'), (2, 'Debit'), (3, 'Transfer'), (4, 'Transfer Duplicate'), (5, 'Reserved Funds')]),
        ),
    ]
