# Generated by Django 4.0.5 on 2022-06-20 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_partialtransactionallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='partialtransactionallocation',
            name='capex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='finance.capex'),
        ),
        migrations.AlterField(
            model_name='partialtransactionallocation',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='partial_transactions', to='finance.allocation'),
        ),
    ]
