# Generated by Django 4.0.5 on 2022-06-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_alter_partialtransactionallocation_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
