# Generated by Django 4.0.5 on 2022-06-20 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_allocation_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartialTransactionAllocation',
            new_name='TransactionAllocation',
        ),
    ]
