# Generated by Django 4.0.5 on 2022-06-20 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_remove_transaction_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionallocation',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='finance.allocation'),
        ),
        migrations.AlterField(
            model_name='transactionallocation',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.transaction'),
        ),
    ]
