# Generated by Django 4.0.5 on 2022-06-20 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_alter_transactionallocation_allocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionallocation',
            name='allocation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='finance.allocation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactioncapex',
            name='capex',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='finance.capex'),
            preserve_default=False,
        ),
    ]
