# Generated by Django 4.0.5 on 2022-06-25 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_alter_transactioncapex_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capexitems',
            name='capex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.capex'),
        ),
        migrations.AlterField(
            model_name='transactioncapex',
            name='capex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='finance.capex'),
        ),
    ]
