# Generated by Django 4.0.5 on 2022-06-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_alter_capexitems_capex_alter_transactioncapex_capex'),
    ]

    operations = [
        migrations.AddField(
            model_name='capexitems',
            name='dateEstimate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
