# Generated by Django 4.0.5 on 2022-06-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_capexitems_dateestimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='capexitems',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
