# Generated by Django 4.0.5 on 2022-07-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0033_capexitems_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Credit'), (2, 'Debit'), (3, 'Transfer'), (4, 'Transfer Duplicate'), (5, 'Reserved Funds'), (6, 'Budget Allocation')]),
        ),
    ]
